### PR TITLE
Setup the CODEOWNERS for pull request reviews

### PR DESCRIPTION
**Pull request by stevehobbsdev**

### CODE REVIEW

**Comment by damieng** [comment]
I'm stepping out of the node roles so we'll need to update this with new primaries/secondaries once we've revisited the matrix after adding new team members.

**Comment by davidpatrick** [comment]
You can put me down as primary

**Comment by stevehobbsdev** [comment]
@davidpatrick I don't mind taking secondary on this, if anyone has any objections?

**Comment by jimmyjames** [comment]
I just took secondary on express-api sample, so could take secondary on this too. Otherwise @stevehobbsdev feel free to take it. We can always change later.

**Pull request merged**
